name: Deploy to VM

on:
  push:
    branches:
      - main # Change this if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0 # Use an exact version if needed

      - name: Install dependencies
        run: npm ci # Faster and more reliable than `npm install`

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.10  # Stable version instead of master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}  # Add this for password authentication
          port: 22
          script: |
            echo "Navigating to the deployment path"
            cd ${{ secrets.DEPLOY_PATH }}

            echo "Fetching the latest code"
            git fetch --all

            echo "Pulling the latest changes from the main branch"
            git pull --rebase origin main # Prevents data loss, safer than reset --hard

            echo "Cleaning npm cache"
            npm cache clean --force

            echo "Installing production dependencies"
            npm install --production

            echo "Reloading PM2 application for zero-downtime restart"
            pm2 reload dw --update-env # Ensure that pm2 is managing the correct app
